### PR TITLE
feat: update exporters

### LINKED ISSUE #57: maintenance: update exporters
Several of the current default exporters are quite old, and some of them are currently deprecated. 

## How?

By reviewing the latest available and maintained version of each exporter, applying any necessary changes to the dashboards, rules and other resources that may be affected.

| Exporter   | Defaulted version                      | Active? | Proposed version                                          | URL                                                                                                             |
| ---------- | -------------------------------------- | ------- | --------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------- |
| cloudwatch | v0.3.0                                 | Yes     | v0.16.0                                                   | [prometheus/cloudwatch_exporter](https://github.com/prometheus/cloudwatch_exporter)                             |
| manticore  | 6.2.13.0                               | Yes     | 6.3.2.0                                                   | [manticoresoftware/manticoresearch-prometheus](https://github.com/manticoresoftware/manticoresearch-prometheus) |
| mysql      | v0.12.1                                | Yes     | v0.14.0                                                   | [prometheus/mysqld_exporter](https://github.com/prometheus/mysqld_exporter)                                     |
| probe      | v0.22.0                                | Yes     | v0.25.0                                                   | [prometheus/blackbox_exporter](https://github.com/prometheus/blackbox_exporter)                                 |
| sendgrid   | 0.0.9                                  | No      | v0.0.10                                                   | [chatwork/sendgrid-stats-exporter](https://github.com/chatwork/sendgrid-stats-exporter)                         |
| es         | justwatch/elasticsearch_exporter:1.1.0 | No      | quay.io/prometheuscommunity/elasticsearch-exporter:v1.8.0 | [prometheus/elasticsearch_exporter](https://github.com/prometheus-community/elasticsearch_exporter)             |
| memcached  | v0.6.0                                 | Yes     | v0.15.0                                                   | [prometheus/memcached_exporter](https://github.com/prometheus/memcached_exporter)                               |
| postgresql | wrouesnel/postgres_exporter:v0.8.0     | No      | quay.io/prometheuscommunity/postgres-exporter:v0.16.0     | [prometheus/postgres_exporter](https://github.com/prometheus-community/postgres_exporter)                       |
| redis      | v1.44.0                                | Yes     | v1.66.0                                                   | [oliver006/redis_exporter](https://github.com/oliver006/redis_exporter)                                         |
| sphinx     | master                                 | Yes     | v0.3.0                                                    | [foxdalas/sphinx_exporter](https://github.com/foxdalas/sphinx_exporter)                                         |

## Requirements

- [x] Review and test the cloudwatch exporter
- [x] Review and test the manticore exporter
- [x] Review and test the mysql exporter
- [x] Review and test the probe exporter
- [x] Review and test the sendgrid exporter
- [x] Review and test the es exporter
- [x] Review and test the memcached exporter
- [x] Review and test the postgresql exporter
- [x] Review and test the redis exporter
- [x] Review and test the sphinx exporter

## Acceptance Criteria

- [ ] Update the default cloudwatch exporter version
- [ ] Update the default manticore exporter version
- [ ] Update the default mysql exporter version
- [ ] Update the default probe exporter version
- [ ] Update the default sendgrid exporter version
- [ ] Update the default es exporter version
- [ ] Update the default memcached exporter version
- [ ] Update the default postgresql exporter version
- [ ] Update the default redis exporter version
- [ ] Update the default sphinx exporter version
- [ ] Make a new prometheus-exporter-operator release with the updated defaults

## Notes

/kind feature
/priority important-longterm
/label size/l

### PR DESCRIPTION
**Pull request by raelga**
- Updates the exporters to the latests compatible version, closes #57 

/kind feature
/priority important-soon
/assign

### CODE REVIEW

**Review by slopezz — CHANGES_REQUESTED** [review]
For the exporters that have changed the repo (I think it was postgre and elasticsearch?), can you please update the repo url at https://github.com/3scale-ops/prometheus-exporter-operator/tree/main/examples ?

**Comment by raelga** [comment]
@slopezz done in https://github.com/3scale-ops/prometheus-exporter-operator/pull/60/commits/c0c351c792a214ee169c25b915f51108933881ac

**Review by slopezz — APPROVED** [review]

**Pull request merged**
